---
- name: install all necessary packages
  gather_facts: true
  become: true
  hosts: 127.0.0.1
  connection: local

  vars:
    ansible_package_manager:
      Fedora: dnf
      Ubuntu: apt

  tasks:
    - name: Debug ansible_distribution
      debug:
        var: ansible_distribution

    - name: Install Python packages for Debian
      apt:
        name:
          - python3
          - python3-pip
          - python3-dev
          - python3-venv
          - python3-setuptools
          - python3-wheel
          - build-essential
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install Python packages for Fedora
      dnf:
        name:
          - python3
          - python3-pip
          - python3-virtualenv
          - python3-setuptools
          - python3-wheel
          - python3-devel
          - python3-pipenv
        state: present
      when: ansible_distribution == 'Fedora'
